lib/globus/client/endpoint.rb
lib/globus/client/identity.rb
spec/globus/client/endpoint_spec.rb
spec/globus/client/identity_spec.rb

Resolves #8 to set permissions for a user on their upload directory. I also changed the former "email" param in some methods to a sunetid, to match what we're usually working with in h2 and did a little refactoring.
Unit tests. 
⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that use sdr-api*** (e.g.create_object_h2_spec.rb) and/or test in [stage|qa] environment, in addition to specs. ⚡

Add ability to set permissions on a globus dir

---

.autoupdate/postupdate
bin/console
globus_client.gemspec
lib/globus/client/unexpected_response.rb

* Use double-quotes around null byte specifier
* Without this commit, the app and its builds were completely broken.
* Fix console binstub
* The console binstub was generated with the wrong path to the client. This commit makes `bin/console` functional. 
```shell
$ bin/console
bin/console:5:in `require': cannot load such file -- globus_client (LoadError)
from bin/console:5:in `<main>'
```
```shell
$ bin/console
3.1.2 :001 >
```
* Add missing standardrb auto-fix update script
* We are currently exploring using standardrb for our Ruby linting needs (instead of plain Rubocop), and part of using standardrb is using its excellent auto-fix functionality when the versions of rubocop and rubocop-performance change behind the scenes. This script was already present in Argo and should be present in …

Fix console binstub and add missing update script

---

lib/globus/client/identity.rb
spec/globus/client/identity_spec.rb

There was a hidden syntax-related error in the Identity service which you can see once we add exception string information to the test:
This commit adds detail to the testing and fixes the bug.
CI

Fix hidden bug in identity service

---

Gemfile.lock
lib/globus/client/endpoint.rb

This commit moves code around and renames things, intended for clarity and to group like information.
* Inline `#call_mkdir` and `#call_access` since they're no longer super-long and they're integral to understanding what `#mkdir` and `#set_permissions` do
* Rename `#endpoint` to `#base_url` so it's clearer what role that method is playing in the class ("yo dawg i herd u like endpoints...")
* Extract `identity` to its own method
CI

Refactor `Endpoint` class

---

spec/globus/client_spec.rb

This commit establishes a new (and hopefully clear) pattern for where and how to test both instance and class methods defined on the `Globus::Client` class.
CI

Tease apart class and instance testing for client

---

README.md
api_test.rb
lib/globus/client.rb
lib/globus/client/endpoint.rb
spec/globus/client/endpoint_spec.rb
spec/globus/client_spec.rb

Fixes #36
This commit adds the ability to disallow writes to a directory (i.e., make a directory read-only) to the public API. As part of this work, add a minor refactoring of the access-related components within the `Endpoint` class for greater code re-use. Also includes:
* Establish a new pattern for streamlined testing of `Client` public API
* Rename `Endpoint#set_permissions` to `Endpoint#allow_writes`
* Allow access changes to handle rule creation and rule updates
* Add and document an integration test for devs.
CI and ran the integration test

Add API for disallowing writes to a directory

---

README.md

This commit changes documentation to reflect current practice around getting environment-specific Globus configuration.
N/A

Update README with more information about how to get configuration values

---

README.md
api_test.rb
bin/console
lib/globus_client.rb
spec/spec_helper.rb

This allows dependent codebases to autoload the gem without requiring an explicit `require "globus/client"`.
CI

Help autoloaders by creating lib/globus_client.rb

---

sig/globus_client.rbs

Tidy things up and stop suggesting we're using type checking.
CI

Remove unused and unnecessary Ruby 3 type signatures

---

README.md
api_test.rb
lib/globus_client/endpoint.rb
lib/globus_client/identity.rb
spec/globus_client/endpoint_spec.rb
spec/globus_client/identity_spec.rb

Fixes #23
Globus transfer operations do not need intimate knowledge of H2 concepts, such as works and versions. Instead, we need a path to operate on. Leave it to consumers like H2 to construct their own relative paths.
Also, decouple the Identity class from needing to know about SUNet IDs and email addresses, and instead expect a working Globus user ID (which just so happens to be a Stanford email).
CI + successful runs of api_test.rb

Refactor endpoint to be less coupled to H2

---

README.md
api_test.rb
lib/globus_client.rb
lib/globus_client/endpoint.rb
spec/globus_client/endpoint_spec.rb
spec/globus_client_spec.rb

Resolves #49 to return a list of files with their absolute filepath, when given an absolute path to a starting directory.
Unit, added tests.
⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that use sdr-api*** (e.g.create_object_h2_spec.rb) and/or test in [stage|qa] environment, in addition to specs. ⚡

Get list of files for a filepath

---

README.md
api_test.rb
lib/globus_client.rb
lib/globus_client/endpoint.rb
spec/globus_client/endpoint_spec.rb
spec/globus_client_spec.rb

This commit reworks the three `Endpoint` methods that need to build up a list of files from an endpoint such that that work---which may be expensive due to needing one request per level of hierarchy---only need be done once.
CI + api_test

Refactor file operations for performance and extensibility

---

lib/globus_client.rb
lib/globus_client/identity.rb
lib/globus_client/token_wrapper.rb
spec/globus_client/identity_spec.rb
spec/globus_client_spec.rb

Resolves [sul-dlss/happy-heron](https://github.com/sul-dlss/happy-heron/issues/2937) to request a new token once upon an API 401 response (UnauthorizedError). 
Unit.
⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that use sdr-api*** (e.g.create_object_h2_spec.rb) and/or test in [stage|qa] environment, in addition to specs. ⚡

Requesting a new token upon UnauthorizedError

---

api_test.rb
lib/globus_client.rb
lib/globus_client/endpoint.rb
spec/globus_client/endpoint_spec.rb
spec/globus_client_spec.rb

* Add ability to ask endpoint if it contains any files
* Supports work in H2 preventing users from depositing works with no Globus files. The recursive endpoint listing can be very expensive, so we expose a new public method for asking if any files are present, short-circuiting the recursive operation as soon as a single file is found.
* Raise exception in Endpoint if supplied a path that is unsplittable
* Fixes a bug that I found while working on a Globus-related feature in H2, caused when consumers fail to provide a valid path argument to endpoint operations.
* Refactor endpoint spec for more idiomatic context/describe usage
* Groups the `Endpoint#list_files` tests together under a single `describe` for the operation, which lets us remove one or two unnecessary levels of nesting and is …

Add ability to ask endpoint if it contains any files

---

.github/pull_request_template.md

Removes sdr-api reference from PR template

tweak to PR template

---

Gemfile.lock
globus_client.gemspec
lib/globus_client.rb
lib/globus_client/endpoint.rb
lib/globus_client/version.rb

We have seen Faraday::ConnectionFailed exceptions in long running
list_files() calls with thousands of recursive API calls. These run
fine in development environments and on Stage, but not in Prod. While we
try to sort out if there is a networking issue we can retry these using faraday-retry.
For context see:
- https://github.com/sul-dlss/happy-heron/issues/3008
- https://github.com/sul-dlss/operations-tasks/issues/3306
Unit tests.
⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Retry failed connections

---

lib/globus_client/endpoint.rb

Fixes https://github.com/sul-dlss/happy-heron/issues/3237
I have been able to verify that this resolves the bug locally via the console. However, I'm a little unclear on how this may be tested (or if it should). I have a small test (not committed yet) that adds the filename that needs to be encoded, but I believe the test in place is mocking the calls to where we're avoiding the URI core calls that actually raise the error.
I'm going to leave this as-is but welcome pairing on testing, either in this PR or a follow up (or if we decide it's unnecessary).
⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to …

Encode filepath to avoid invalid uri errors

---

lib/globus_client/endpoint.rb
spec/globus_client/endpoint_spec.rb

Upon further reflection, the `disallow_writes` method should raise an error if you're trying to update a rule that does not exist. Also, the tests had been set up to pass when they should have failed in these cases. 
Unit and QA deploy. Gem has no change to the public method and it's OK for this to be in the next release, which will also include deleting access rules. 
⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Raise error when no access rule to change

---

lib/globus_client.rb
lib/globus_client/endpoint.rb
spec/globus_client/endpoint_spec.rb
spec/globus_client_spec.rb

Resolves #95 to add a way to remove access to an endpoint. 
After this is merged, we should cut a new release.
Unit tests and called from rails console from H2. Users will see "permission denied" on an endpoint that has its rule removed. 
⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Delete access rule

---

api_test.rb
lib/globus_client.rb
spec/globus_client_spec.rb

For the initial token, use a dummy value to avoid hitting any APIs during configuration, allowing the `TokenWrapper` to handle auto-magic token refreshing. Why not immediately get a valid token? Our apps commonly invoke client `.configure` methods in the initializer in all application environments, even those that are never expected to connect to production APIs, such as local development machines.
NOTE: `nil` and blank string cannot be used as dummy values here as they lead to a malformed request to be sent, which triggers an exception not rescued by `TokenWrapper`
CI, ran `api_test.rb` successfully

Do not authenticate as part of client configuration

---

lib/globus_client/endpoint.rb
lib/globus_client/unexpected_response.rb
spec/globus_client/endpoint_spec.rb

Fixes #113 - use the `UnexpectedResponse` exception when an error occurs, so it can be correctly caught by the `TokenRefresh` logic.  Add in the ability to pass in a custom message for logging the exception too.
Added a new spec

raise UnexpectedResponse when an error occurs

---

lib/globus_client/endpoint.rb
spec/globus_client/endpoint_spec.rb

Allow consumers of the client to ask Globus to skip sending emails.  Defaults to "true" so will send email unless you opt out when initializing the client.
New spec

allow the user to skip notifying email

---

lib/globus_client.rb
lib/globus_client/authenticator.rb
lib/globus_client/endpoint.rb
lib/globus_client/identity.rb
spec/globus_client/authenticator_spec.rb
spec/globus_client/endpoint_spec.rb
spec/globus_client/identity_spec.rb
spec/globus_client_spec.rb

The `Endpoint`, `Authenticator`, and `Identity` classes all rely on the `GlobusClient` singleton instance already, and the instance injected at instantiation time is in practice identical to the one that is accessible via `GlobusClient.instance`, so simplify interfaces and dependencies by relying directly on the singleton instead of passing stuff around.
CI

Prefer using the singleton instance over passing around instance and config objects

---

Gemfile.lock
globus_client.gemspec

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Loosen activesupport pin to allow Rails 8 upgrades
